BlogApp.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        private ICategoryRepository _categoryRepository;
        public BlogController(IBlogRepository blogRepo, ICategoryRepository categoryRepo)
        {
            _blogRepository = blogRepo;
            _categoryRepository = categoryRepo;
        }

        public IActionResult Details(int id)
        {
            return View(_blogRepository.GetById(id));
        }
        public IActionResult Index(int? id,string q )
        {
            var query = _blogRepository.GetAll().Where(p => p.isApproved);
            if (id != null)
            {
                query = query.Where(i => i.CategoryId == id);
            }
            if (!string.IsNullOrEmpty(q))
            {
                query = query.Where(i => EF.Functions.Like(i.Title, "%"+q+"%") || EF.Functions.Like(i.Description, "%" + q + "%") || EF.Functions.Like(i.Body, "%" + q + "%"));
            }
            return View(query.OrderByDescending(i => i.Date));
        }
        public IActionResult List()
        {
            return View(_blogRepository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
                ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
                return View(new Blog());
        }
        [HttpPost]
        public IActionResult Create(Blog entity)
        {
            if (ModelState.IsValid)
            {
                _blogRepository.SaveBlog(entity);
                TempData["message"] = $"{entity.Title} kayıt edildi.";
                ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(_blogRepository.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                        entity.Image = file.FileName;
                    }
                }

                _blogRepository.SaveBlog(entity);
                TempData["message"] = $"{entity.Title} kayıt edildi.";
                ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_blogRepository.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int BlogId)
        {
            _blogRepository.DeleteBlog(BlogId);
            TempData["message"] = $"{BlogId} numaralı kayıt edildi.";
            return RedirectToAction("List");
        }
    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryRepository _repository;

        public CategoryMenuViewComponent(ICategoryRepository repo)
        {
            _repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(_repository.GetAll());
        }
    }
}

BlogApp.WebUI/Views/Blog/AddOrUpdate.cshtml
@model Blog
@{
    ViewData["Title"] = "AddOrUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h1>Create Blog</h1>
    <br />

    <form asp-controller="Blog" asp-action="AddOrUpdate" method="post">
        <input type="hidden" asp-for="BlogId" />
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"> </textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control"> </textarea>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control">
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input">is Approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input">is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input">is Slider
            </label>
        </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control"
                        asp-items="ViewBag.Categories">
                    <option disabled selected value="">Select Category</option>
                </select>
            </div>
            <button class="btn btn-primary" type="submit">Gönder</button>

    </form>
</div>

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h1>Create Blog</h1>
    <br />

    <form asp-controller="Blog" asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"> </textarea>
        </div>

        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control"
                    asp-items="ViewBag.Categories">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Kaydet</button>

    </form>
</div>

BlogApp.WebUI/Views/Blog/Delete.cshtml
@model Blog
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>
    <b>@Model.Title</b>İsimli kaydı silmek istiyor musunuz?
</h1>

<form asp-action="Delete" asp-controller="Blog" method="post">
    <input type="hidden" asp-for="BlogId"/>   
    <button type="submit" class="btn btn-primary">Delete</button>
</form> 

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <div class="card mt-3">
                <div class="card-header">
                    @Model.Title
                </div>
                <img src="~/img/@Model.Image" class="card-img-top" alt="...">

                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section scripts{ 
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Body")
    </script>
}
<div class="container">
    <h1>Edit Blog</h1>
    <br />

    <form asp-controller="Blog" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="BlogId" />
        <input type="hidden" asp-for="Image" />

        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"> </textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control"> </textarea>
        </div>
        <div class="form-group">
            <img src="~/img/@Model.Image" width="120" />
            <input type="file" name="file" id="file" class="form-control">
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input">is Approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input">is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input">is Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control"
                    asp-items="ViewBag.Categories">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Gönder</button>

    </form>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList", Model)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="container mt-3">
        <h1>Blog Listesi</h1>
        <hr />
        <div>
            <a class="btn btn-primary" href="/blog/create">Create</a>
        </div>
        <hr />
        <div class="row">
            <div class="col">
                @if (Model.Count() > 0)
                {
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Date</th>
                                <th>is Approved</th>
                                <th>is Home</th>
                                <th>is Slider</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.BlogId</td>
                                <td><img src="~/img/@item.Image" width="100" /></td>
                                <td>@item.Title</td>
                                <td>@item.Date</td>
                                <td>
                                    @if (item.isApproved)
                                    {
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    }
                                </td>
                                <td>
                                    @if (item.isHome)
                                    {
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    }
                                </td>
                                <td>
                                    @if (item.isSlider)
                                    {
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    }
                                </td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Edit" asp-route-id="@item.BlogId">
                                        Edit
                                    </a>
                                    <a class="btn btn-danger btn-sm" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.BlogId">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                     }
                else
                {
                    <div class="alert alert-danger">
                        Blog Eklenmemiş
                    </div>
                }
            </div>
        </div>
    </div>